spring:
  #  elasticsearch:
  ##    username: elastic
  ##    password: 123456
  #    uris: http://${ES_HOST:192.168.28.132}:${ES_PORT:9200}
  #    connection-timeout: 1s
  #    read-timeout: 30s
  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27019/mpcs-dev?authSource=admin
      database: mpcs-dev
    redis:
      database: 0
      host: localhost
      port: 6379
      password: "123456"
      timeout: 3000
      jedis:
        pool:
          max-idle: 500
          min-idle: 50
          max-active: 2000
          max-wait: 1000
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB

#cloud:
#  elasticsearch:
#    host: ${ES_HOST:192.168.28.132}
#    port: ${ES_PORT:9200}

mpcs:
  config:
    enable-limit-rate: false
    base-domain-name: ci.ricky.com
  jwt:
    issuer: mpcs-local-issuer
    secret: ckxGdnjP6bGmQyrGJaW32s8CtxyGVgeK
    expire: 720
    ahead-auto-refresh: 60
  redis:
    domain-event-stream-prefix: DomainEvent.LOCAL
    domain-event-stream-count: 10
    notification-stream: Notification.LOCAL
    webhook-stream: Webhook.LOCAL
  file:
    hash:
      algorithm: SHA256
    upload:
      chunk-dir: "F:\\Develop\\java\\mpcs\\mpcs-backend\\mod-api-test\\src\\test\\resources\\chunk-path"
      chunk-size: 1048576  # 1MB
      buffer-size: 1048576  # 1MB
  common:
    https-enabled: false
    base-domain-name: mpcs.com  # TODO
    limit-rate: false
