spring:
  #  elasticsearch:
  ##    username: elastic
  ##    password: 123456
  #    uris: http://${ES_HOST:192.168.28.132}:${ES_PORT:9200}
  #    connection-timeout: 1s
  #    read-timeout: 30s
  data:
    mongodb:
      #      uri: mongodb://admin:123456@localhost:27020,localhost:27018,localhost:27019/mpcs-dev?replicaSet=app&authSource=admin
      uri: mongodb://admin:123456@localhost:27018/mpcs-dev?authSource=admin
      database: mpcs-dev
    redis:
      database: 0
      host: localhost
      port: 6379
      password: "123456"
      timeout: 3000
      jedis:
        pool:
          max-idle: 500
          min-idle: 50
          max-active: 2000
          max-wait: 1000
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB

#cloud:
#  elasticsearch:
#    host: ${ES_HOST:192.168.28.132}
#    port: ${ES_PORT:9200}

mpcs:
  config:
    enable-limit-rate: false
    base-domain-name: ci.ricky.com
  jwt:
    issuer: mry-local-issuer
    secret: EHnbNd1KxkXceo9v
    expire: 720
    aheadAutoRefresh: 60
  redis:
    domainEventStreamEnabled: false
    domainEventStreamPrefix: DomainEvent.LOCAL
    domainEventStreamCount: 10
    notificationStream: Notification.LOCAL
    webhookStream: Webhook.LOCAL
  file:
    hash:
      algorithm: SHA256
  common:
    httpsEnabled: false
    baseDomainName: mpcs.com  # TODO
    limitRate: false
