spring:
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1s
  data:
    mongodb:
      uri: ${MPCS_MONGO_URI}
      database: ${MPCS_MONGO_DB:mpcs-dev}
    redis:
      database: 0
      host: localhost
      port: 6379
      password: ${MPCS_REDIS_PASSWORD}
      timeout: 3000
      jedis:
        pool:
          max-idle: 500
          min-idle: 50
          max-active: 2000
          max-wait: 1000
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB
  ai:
    retry:
      max-attempts: 3
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
          temperature: 0.7

management:
  health:
    elasticsearch:
      enabled: false  # 禁用默认的健康检查

logging:
  level:
    com.alibaba.cloud.ai.dashscope.api: DEBUG

mpcs:
  config:
    limit-rate: false
    base-domain-name: mpcs.com  # TODO
    https-enabled: false
    auth: true
    storage: OSS
  jwt:
    issuer: mpcs-local-issuer
    secret: ${MPCS_JWT_SECRET}
    expire: 720
    ahead-auto-refresh: 60
  redis:
    domain-event-stream-enabled: true
    domain-event-stream-prefix: DomainEvent.LOCAL
    domain-event-stream-count: 10
    notification-stream: Notification.LOCAL
    webhook-stream: Webhook.LOCAL
  file:
    hash:
      algorithm: SHA256
    upload:
      chunk-dir: "F:\\Develop\\java\\mpcs\\mpcs-backend\\data\\chunks"
      chunk-size: 1048576  # 1MB
      buffer-size: 1048576  # 1MB
    text-file-dir: "F:\\Develop\\java\\mpcs\\mpcs-backend\\data\\text-files"
  sensitive:
    algorithm: DFA
  minio:
    endpoint: http://localhost:9000
    access-key: ${MPCS_MINIO_ACCESS_KEY}
    secret-key: ${MPCS_MINIO_SECRET_KEY}
