spring:
  elasticsearch:
    # username: elastic
    # password: 123456
    uris: http://localhost:9200
    connection-timeout: 1s
  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27018/mpcs-dev?authSource=admin
      database: mpcs-dev
    redis:
      database: 0
      host: localhost
      port: 6379
      password: "123456"
      timeout: 3000
      jedis:
        pool:
          max-idle: 500
          min-idle: 50
          max-active: 2000
          max-wait: 1000
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
          max-tokens: 2000

management:
  health:
    elasticsearch:
      enabled: false  # 禁用默认的健康检查

#cloud:
#  elasticsearch:
#    host: ${ES_HOST:192.168.28.132}
#    port: ${ES_PORT:9200}

mpcs:
  config:
    enable-limit-rate: false
    base-domain-name: ci.ricky.com
  jwt:
    issuer: mpcs-local-issuer
    secret: ckxGdnjP6bGmQyrGJaW32s8CtxyGVgeK
    expire: 720
    ahead-auto-refresh: 60
  redis:
    domain-event-stream-enabled: true
    domain-event-stream-prefix: DomainEvent.LOCAL
    domain-event-stream-count: 10
    notification-stream: Notification.LOCAL
    webhook-stream: Webhook.LOCAL
  file:
    hash:
      algorithm: SHA256
    upload:
      chunk-dir: "F:\\Develop\\java\\mpcs\\mpcs-backend\\mod-api-test\\src\\test\\resources\\chunk-path"
      chunk-size: 1048576  # 1MB
      buffer-size: 1048576  # 1MB
    text-file-path: "F:\\Develop\\java\\mpcs\\mpcs-backend\\mod-api-test\\src\\test\\resources\\text-file-path"
  common:
    https-enabled: false
    base-domain-name: mpcs.com  # TODO
    limit-rate: false
