server:
  port: 8082
  servlet:
    context-path: /api/v1.0

spring:
  application:
    name: mpcs-backend
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  profiles:
    active: ci
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      ansj: DEBUG  # TODO 这里配置不了日志级别
      com.alibaba.cloud.ai.dashscope: DEBUG
