version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    command: [ "redis-server", "/etc/redis/redis.conf", "--requirepass", "123" ]
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "123", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/keyFile:/opt/keyfile
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    command: |
      --replSet rs0
      --bind_ip_all
      --keyFile /opt/keyfile/keyFile
      --auth
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "-u", "admin", "-p", "123456", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge