version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    command: [ "redis-server", "/etc/redis/redis.conf", "--requirepass", "123456" ]
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "123456", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo1:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb1
    command: --replSet app --bind_ip_all --keyFile /data/mongodb/keyFile
    environment:
      TZ: 'Asia/Shanghai'
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: '123456'
    ports:
      - "27020:27017"  # 宿主机:容器端口
    volumes:
      - ./data1:/data/db
      - ./keyFile:/data/mongodb/keyFile
    networks:
      app-network:
        aliases:
          - mongo1.local  # 网络别名，容器间通信使用
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongo2:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb2
    command: --replSet app --bind_ip_all --keyFile /data/mongodb/keyFile
    environment:
      TZ: 'Asia/Shanghai'
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: '123456'
    ports:
      - "27018:27017"  # 宿主机:容器端口
    volumes:
      - ./data2:/data/db
      - ./keyFile:/data/mongodb/keyFile
    networks:
      app-network:
        aliases:
          - mongo2.local  # 网络别名，容器间通信使用
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongo3:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb3
    command: --replSet app --bind_ip_all --keyFile /data/mongodb/keyFile
    environment:
      TZ: 'Asia/Shanghai'
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: '123456'
    ports:
      - "27019:27017"  # 宿主机:容器端口
    volumes:
      - ./data3:/data/db
      - ./keyFile:/data/mongodb/keyFile
    networks:
      app-network:
        aliases:
          - mongo3.local  # 网络别名，容器间通信使用
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongo-init:
    image: mongo:latest
    container_name: mongo-init
    restart: "no"  # 只运行一次
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
    volumes:
      - ./init-script.sh:/init-script.sh
      - ./keyFile:/data/mongodb/keyFile
    entrypoint: [ "sh", "/init-script.sh" ]
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node # 单节点模式
      - xpack.security.enabled=false # 禁用安全认证，简化本地开发连接[citation:4]
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # 设置JVM堆内存大小
      - TZ=Asia/Shanghai
    ports:
      - "9200:9200" # REST API端口
      - "9300:9300" # 集群通信端口（通常用不到）
    volumes:
      - ./es/data:/usr/share/elasticsearch/data # 数据持久化
    #      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml # 自定义配置
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "-u", "elastic:changeme", "http://localhost:9200/_cluster/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

#  kibana:
#    image: kibana:8.13.0
#    container_name: kibana
#    restart: unless-stopped
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#      - TZ=Asia/Shanghai
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge